/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_chinaxing_IoURingNative */

#ifndef _Included_org_chinaxing_IoURingNative
#define _Included_org_chinaxing_IoURingNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_chinaxing_IoURingNative
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_chinaxing_IoURingNative_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_chinaxing_IoURingNative
 * Method:    init0
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_org_chinaxing_IoURingNative_init0
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     org_chinaxing_IoURingNative
 * Method:    exit0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_chinaxing_IoURingNative_exit0
  (JNIEnv *, jobject);

/*
 * Class:     org_chinaxing_IoURingNative
 * Method:    registerBuffers
 * Signature: ([J[J)I
 */
JNIEXPORT jint JNICALL Java_org_chinaxing_IoURingNative_registerBuffers
  (JNIEnv *, jobject, jlongArray, jlongArray);

/*
 * Class:     org_chinaxing_IoURingNative
 * Method:    unregisterBuffers
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_chinaxing_IoURingNative_unregisterBuffers
  (JNIEnv *, jobject);

/*
 * Class:     org_chinaxing_IoURingNative
 * Method:    registerFiles
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_org_chinaxing_IoURingNative_registerFiles
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     org_chinaxing_IoURingNative
 * Method:    unregisterFiles
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_chinaxing_IoURingNative_unregisterFiles
  (JNIEnv *, jobject);

/*
 * Class:     org_chinaxing_IoURingNative
 * Method:    prepareRead
 * Signature: (JJIJIJ)I
 */
JNIEXPORT jint JNICALL Java_org_chinaxing_IoURingNative_prepareRead
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint, jlong);

/*
 * Class:     org_chinaxing_IoURingNative
 * Method:    prepareReads
 * Signature: (JJI[J[IJ)I
 */
JNIEXPORT jint JNICALL Java_org_chinaxing_IoURingNative_prepareReads
  (JNIEnv *, jobject, jlong, jlong, jint, jlongArray, jintArray, jlong);

/*
 * Class:     org_chinaxing_IoURingNative
 * Method:    prepareReadFixed
 * Signature: (JJIJIJI)I
 */
JNIEXPORT jint JNICALL Java_org_chinaxing_IoURingNative_prepareReadFixed
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint, jlong, jint);

/*
 * Class:     org_chinaxing_IoURingNative
 * Method:    prepareWrite
 * Signature: (JJIJIJ)I
 */
JNIEXPORT jint JNICALL Java_org_chinaxing_IoURingNative_prepareWrite
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint, jlong);

/*
 * Class:     org_chinaxing_IoURingNative
 * Method:    prepareWrites
 * Signature: (JJI[J[IJ)I
 */
JNIEXPORT jint JNICALL Java_org_chinaxing_IoURingNative_prepareWrites
  (JNIEnv *, jobject, jlong, jlong, jint, jlongArray, jintArray, jlong);

/*
 * Class:     org_chinaxing_IoURingNative
 * Method:    prepareWriteFixed
 * Signature: (JJIJIJI)I
 */
JNIEXPORT jint JNICALL Java_org_chinaxing_IoURingNative_prepareWriteFixed
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint, jlong, jint);

/*
 * Class:     org_chinaxing_IoURingNative
 * Method:    prepareFsync
 * Signature: (JJIJ)I
 */
JNIEXPORT jint JNICALL Java_org_chinaxing_IoURingNative_prepareFsync
  (JNIEnv *, jobject, jlong, jlong, jint, jlong);

/*
 * Class:     org_chinaxing_IoURingNative
 * Method:    submit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_chinaxing_IoURingNative_submit
  (JNIEnv *, jobject);

/*
 * Class:     org_chinaxing_IoURingNative
 * Method:    submitAndWait
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_chinaxing_IoURingNative_submitAndWait
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_chinaxing_IoURingNative
 * Method:    waitCQEntryTimeout
 * Signature: ([J[JJ)I
 */
JNIEXPORT jint JNICALL Java_org_chinaxing_IoURingNative_waitCQEntryTimeout
  (JNIEnv *, jobject, jlongArray, jlongArray, jlong);

/*
 * Class:     org_chinaxing_IoURingNative
 * Method:    waitCQEntries
 * Signature: ([J[JI)I
 */
JNIEXPORT jint JNICALL Java_org_chinaxing_IoURingNative_waitCQEntries
  (JNIEnv *, jobject, jlongArray, jlongArray, jint);

/*
 * Class:     org_chinaxing_IoURingNative
 * Method:    peekCQEntries
 * Signature: ([J[JI)I
 */
JNIEXPORT jint JNICALL Java_org_chinaxing_IoURingNative_peekCQEntries
  (JNIEnv *, jobject, jlongArray, jlongArray, jint);

/*
 * Class:     org_chinaxing_IoURingNative
 * Method:    advanceCQ
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_chinaxing_IoURingNative_advanceCQ
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
