/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_chinaxing_IoURing */

#ifndef _Included_org_chinaxing_IoURing
#define _Included_org_chinaxing_IoURing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_chinaxing_IoURing
 * Method:    init0
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_org_chinaxing_IoURing_init0
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     org_chinaxing_IoURing
 * Method:    exit0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_chinaxing_IoURing_exit0
  (JNIEnv *, jobject);

/*
 * Class:     org_chinaxing_IoURing
 * Method:    getSqe
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_chinaxing_IoURing_getSqe
  (JNIEnv *, jobject);

/*
 * Class:     org_chinaxing_IoURing
 * Method:    registerBuffers
 * Signature: ([J[J)I
 */
JNIEXPORT jint JNICALL Java_org_chinaxing_IoURing_registerBuffers
  (JNIEnv *, jobject, jlongArray, jlongArray);

/*
 * Class:     org_chinaxing_IoURing
 * Method:    unRegisterBuffers
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_chinaxing_IoURing_unRegisterBuffers
  (JNIEnv *, jobject);

/*
 * Class:     org_chinaxing_IoURing
 * Method:    prepRead
 * Signature: (JIJJJ)V
 */
JNIEXPORT void JNICALL Java_org_chinaxing_IoURing_prepRead
  (JNIEnv *, jobject, jlong, jint, jlong, jlong, jlong);

/*
 * Class:     org_chinaxing_IoURing
 * Method:    prepWrite
 * Signature: (JIJJJ)V
 */
JNIEXPORT void JNICALL Java_org_chinaxing_IoURing_prepWrite
  (JNIEnv *, jobject, jlong, jint, jlong, jlong, jlong);

/*
 * Class:     org_chinaxing_IoURing
 * Method:    prepReadFixed
 * Signature: (JIJJJI)V
 */
JNIEXPORT void JNICALL Java_org_chinaxing_IoURing_prepReadFixed
  (JNIEnv *, jobject, jlong, jint, jlong, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
